@startuml

start

:Fastställ starttidpunkt;

:Startdagen räknas inte;

if (Vilken typ av tidsfrist?) then (Dagar)

    :Lägg till antal dagar;

elseif (Veckor)

    :Lägg till antal veckor;

    :Samma veckodag;

elseif (Månader)

    :Lägg till antal månader;

    if (Datum finns?) then (Ja)

        :Samma datum;

    else (Nej)

        :Månadens sista dag;

    endif

endif

if (Sista dagen\när helgdag?) then (Ja)

    :Flytta till\nnästa arbetsdag;

endif

:Fristen löper ut\n24:00;

stop

@enduml