@startuml
title Från manuell hantering till orkestrerad intervju

start

partition "Intervjuare" {
    :Ange vad som behöver bokas;
}

partition "Vår applikation" {

    :Sök personal,
    lokaler och resurser;

    :Kontrollera tillgänglighet;

    :Hitta bästa möjliga tid;

    :Boka resurser;

    :Skapa och konfigurera
    Zoom-möte;

    :Skapa Outlook-möte;
}

partition "Intervju" {
    :Genomför intervju;
}

partition "Vår applikation" {

    :Ta emot händelser från Zoom;

    :Hantera inspelning;

    :Skicka ljud och information
    till efterföljande system;
}

stop

@enduml